from enum import Enum


class ProductCategory(Enum):
    ENGINE_COMPONENTS = "ENGINE_COMPONENTS"
    TRANSMISSION = "TRANSMISSION"
    ELECTRICAL_SYSTEMS = "ELECTRICAL_SYSTEMS"
    BRAKES = "BRAKES"
    INTERIOR_COMPONENTS = "INTERIOR_COMPONENTS"
    EXHAUST_SYSTEMS = "EXHAUST_SYSTEMS"
    COOLING_SYSTEMS = "COOLING_SYSTEMS"
    LIGHTING_SYSTEMS = "LIGHTING_SYSTEMS"
    ACCESSORIES = "ACCESSORIES"
